name: Deploy CNRT Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # 🔹 actualizado a v4

      - name: Setup Pages
        uses: actions/configure-pages@v4   # 🔹 actualizado a v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3   # 🔹 actualizado a v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4   # 🔹 actualizado a v4
